[www]
    host = "127.0.0.1"
    port = 5050
    postsize = "5MB"

    cookieName = "REG_MANAGER_SESS"
    csrfCookie = "REG_MANAGER_CSRF"

[users]
    # must be readable/writable by application
    db="./config/users.json"

[registry]
    scope="@myscope"
    url="http://localhost:4873"
